config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :tasks do
    member do
      post :complete
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates_presence_of :event_type, :data
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  validates_presence_of :description
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    tasks_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate

  def index
    @tasks = current_user.tasks
  end

  def new
    @task = Task.new
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.description = params[:task][:description]

    if @task.save
      redirect_to tasks_path
    else
      render :edit
    end
  end

  def create
    @task = Task.new(description: params[:task][:description], user: current_user)

    if @task.save
      redirect_to tasks_path
    else
      render :new
    end
  end

  def destroy
    @task = Task.find(params[:id])

    @task.destroy

    redirect_to tasks_path
  end

  def complete
    @task = Task.find(params[:id])
    @task.completed_at = Time.current

    email_random_params = Task::CompletedEmailParams.call

    @task.transaction do
      @task.save!
      Event.create!(
        event_type: 'task_completed',
        data: {
          task_id: @task.id,
          message: email_random_params.message,
          message_color: email_random_params.message_color
        }
      )
      TaskMailer.with(
        task_id: @task.id,
        message: email_random_params.message,
        message_color: email_random_params.message_color
      ).completed.deliver_later
    end

    redirect_to tasks_path
  end

  private

  def authenticate
    redirect_to new_user_session_path if current_user.blank?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorldpackersTodo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.slim
= simple_form_for @task do |f|
  = f.input :description
  - if @task.persisted?
    = f.submit 'Update task', class: 'btn btn-success float-right'
  - else
    = f.submit 'Create task', class: 'btn btn-success float-right'

app/views/tasks/edit.html.slim
h1 Edit Task
= render partial: 'form'

app/views/tasks/index.html.slim
.row
  .col-10
    h1 Tasks
    ul
      - @tasks.each do |task|
        li
          = task.description
          - if task.completed_at.present?
            |  (Complete)
          - else
            = link_to 'Complete', complete_task_path(id: task.id), method: :post, class: "btn btn-success btn-sm ml-1 cpy-complete-task-#{task.id}"
          = link_to 'Edit', edit_task_path(id: task.id), class: "btn btn-primary btn-sm ml-1 cpy-edit-task-#{task.id}"
          = link_to 'Delete', task_path(id: task.id), method: :delete, class: "btn btn-danger btn-sm ml-1 cpy-delete-task-#{task.id}"
  .col-2
    = link_to 'New', new_task_path, class: "btn btn-success btn-sm mt-1 float-right"

app/views/tasks/new.html.slim
h1 New Task
= render partial: 'form'